services:
  couchdb:
    image: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - type: bind
        source: ../couchdb/data
        target: /opt/couchdb/data
      - type: bind
        source: ../couchdb/local.d
        target: /opt/couchdb/etc/local.d