x-common-environment: &common-env
  COUCHDB_USER: admin
  COUCHDB_PASSWORD: password

services:
  discount-discovery:
    build: .
    ports:
      - "3000:3000"
    environment:
      <<: *common-env
      DISCOUT_DISCOVERY_DB_URL: http://couchdb:5984
      DISCOUT_DISCOVERY_DB_SETUP: true
    depends_on: 
      couchdb:
        condition: service_healthy

  couchdb:
    image: couchdb
    ports:
      - "5984:5984"
    environment:
      <<: *common-env
    volumes:
      - type: bind
        source: ../couchdb/data
        target: /opt/couchdb/data
      - type: bind
        source: ../couchdb/local.d
        target: /opt/couchdb/etc/local.d
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 10s
      timeout: 5s
      retries: 5
  
