// Generated by ts-to-zod
import { z } from "zod";
import {
  type ShopConfig,
  type ParseStep,
  type ForEachParameters,
  type IfParameters,
  stepType,
} from "./../types/shopConfig";

export const stepTypeSchema = z.nativeEnum(stepType);

export const argumentSchema = z.object({
  argument: z.string(),
  label: z.string(),
  required: z.boolean().optional(),
  defaultValue: z.string().optional(),
});

export const fetchParametersSchema = z.object({
  method: z.literal(stepType.Fetch),
  headersSource: z.string().optional(),
});

export const literalParametersSchema = z.object({
  method: z.literal(stepType.Literal),
  data: z.string(),
  destination: z.string().optional(),
});

export const setPropParametersSchema = z.object({
  method: z.literal(stepType.SetProp),
  source: z.string().optional(),
  destination: z.string().optional(),
});

export const parseJSONParametersSchema = z.object({
  method: z.literal(stepType.ParseJSON),
});

export const createArrayParametersSchema = z.object({
  method: z.literal(stepType.CreateArray),
  name: z.string(),
});

export const pushToArrayParametersSchema = z.object({
  method: z.literal(stepType.PushToArray),
  array: z.string(),
  data: z.string().optional(),
});

export const parseHTMLParametersSchema = z.object({
  method: z.literal(stepType.ParseHTML),
});

export const hTMLQuerySelectorParametersSchema = z.object({
  method: z.literal(stepType.HTMLQuerySelector),
  all: z.boolean().optional(),
  selector: z.string(),
});

export const concatParametersSchema = z.object({
  method: z.literal(stepType.Concat),
  first: z.string().optional(),
  second: z.string().optional(),
});

export const toStringParametersSchema = z.object({
  method: z.literal(stepType.ToString),
});

export const hTMLCloneParametersSchema = z.object({
  method: z.literal(stepType.HTMLClone),
  destination: z.string(),
});

export const deepCopyParametersSchema = z.object({
  method: z.literal(stepType.DeepCopy),
});

export const sliceParametersSchema = z.object({
  method: z.literal(stepType.Slice),
  start: z.number(),
  end: z.number().optional(),
});

export const splitParametersSchema = z.object({
  method: z.literal(stepType.Split),
  separator: z.string().optional(),
  limit: z.number().optional(),
});

export const replaceParametersSchema = z.object({
  method: z.literal(stepType.Replace),
  searchValue: z.string(),
  newValue: z.string(),
  all: z.boolean().optional(),
});

export const spreadParametersSchema = z.object({
  method: z.literal(stepType.Spread),
  first: z.string().optional(),
  second: z.string().optional(),
});

export const shopConfigSchema: z.ZodSchema<ShopConfig> = z.lazy(() =>
  z.object({
    autoCorrectYears: z.boolean().optional(),
    name: z.string(),
    cron: z.string().optional(),
    timezone: z.string().optional(),
    icon: z.string().optional(),
    arguments: z.array(argumentSchema).optional(),
    steps: z.array(parseStepSchema),
  }),
);

export const parseStepSchema: z.ZodSchema<ParseStep> = z.lazy(() =>
  z.object({
    stepParameters: z.union([
      fetchParametersSchema,
      literalParametersSchema,
      setPropParametersSchema,
      parseJSONParametersSchema,
      forEachParametersSchema,
      createArrayParametersSchema,
      pushToArrayParametersSchema,
      parseHTMLParametersSchema,
      hTMLQuerySelectorParametersSchema,
      concatParametersSchema,
      toStringParametersSchema,
      hTMLCloneParametersSchema,
      deepCopyParametersSchema,
      sliceParametersSchema,
      splitParametersSchema,
      replaceParametersSchema,
      spreadParametersSchema,
      ifParametersSchema,
    ]),
  }),
);

export const forEachParametersSchema: z.ZodSchema<ForEachParameters> = z.lazy(
  () =>
    z.object({
      method: z.literal(stepType.ForEach),
      source: z.string(),
      steps: z.array(parseStepSchema),
    }),
);

export const ifParametersSchema: z.ZodSchema<IfParameters> = z.lazy(() =>
  z.object({
    method: z.literal(stepType.If),
    data: z.string().optional(),
    steps: z.array(parseStepSchema),
    elseSteps: z.array(parseStepSchema).optional(),
  }),
);
